version: "3"

services:
  tf_serve:
    build: ./serving
    environment:
      - MODEL_NAME=tftransfer
    ports:
      - 8501:8501

  flask_app:
    build: ./python
    volumes:
      - ./python:/root/app
    working_dir: /root/app   
    command: python3 app.py
    ports:
      - 5000:5000
    depends_on:
      - tf_serve